header-includes:
  - \usepackage{float} # if figures?¿
bibliography: ML-1-bib.bib # add bibliography
link-citations: true
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
    latex_engine: xelatex
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

```{r packagesBIOC, message=FALSE, echo=FALSE, warning=FALSE}
bioc_packages <- c(
  "TCGAbiolinks",
  "SummarizedExperiment",
  "edgeR",
  "limma",
  "DESeq2",
  "ComplexHeatmap",
  "maftools"
)

for (pkg in bioc_packages) {
  if (!requireNamespace(pkg, quietly = TRUE))
    BiocManager::install(pkg)
}
```

```{r packagesCRAN, message=FALSE, echo=FALSE, warning=FALSE}
packages <- c("tidyverse",
              "here",
              "renv",
              "janitor",
              "pheatmap",
              "survminer")

for (pkg in packages) {
  if (!requireNamespace(pkg, quietly = TRUE))
    install.packages(pkg)
}
```

```{r libraries, include=FALSE}
# Load packages
library(TCGAbiolinks)
library(tidyverse)
library(maftools)
library(pheatmap)
library(SummarizedExperiment)
```

```{r query-one}
# building a query --------------------------------------------------------
query_clinical <- GDCquery(project = 'TCGA-STAD',
                       data.category = 'Clinical',
                       disease.type = 'adenomas and adenocarcinomas',
                       access = 'open')

clinical <- getResults(query_clinical)
dim(clinical)
head(clinical)
```

```{r download}
# download data -----------------------------------------------------------
# first, in order to protect personal data, a .Renviron will be created.
dir <- #my personal directory 
GDCdownload(query_clinical,
            directory = "dir"
            )

# the download goes to a file where all TCGA data is being saved, so it can be used
# in any other projects.
```

```{r prepare-data}
# prepare data ------------------------------------------------------------
tcga_se <- GDCprepare(query_TCGA, summarizedExperiment = TRUE)
```

```{r input}
# el objeto preparado (se) se guarda también en la carpeta de "preparados" por si lo queremos
# usar en otro proyecto.

saveRDS(tcga_se,
        "dir"
        )

# principal matrix of the se
stad_matrix <- assay(tcga_se, 'assay-we-want-to-retrieve-from-se')

colData(tcga_se)
rowData(tcga_se)
```